name: manhole_detector
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+7
  flutter_vision: ^1.1.4
  image: ^4.2.0
  image_picker: ^1.0.7
  get: ^4.6.6
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  google_maps_flutter: ^2.1.10
  location: ^6.0.2
  geolocator: ^12.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  latlong2: ^0.9.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/manhole.db
